fix(build): cd secrets

diff --git a/.github/workflows/cd-release.yml b/.github/workflows/cd-release.yml
--- a/.github/workflows/cd-release.yml
+++ b/.github/workflows/cd-release.yml
@@ -45,9 +45,9 @@ env:
 
   # 🖊️ EDIT to change the image registry settings.
   # Registries such as GHCR, Quay.io, and Docker Hub are supported.
-  IMAGE_REGISTRY: ${{ secrets.QUAY_REGISTRY }}
-  IMAGE_REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
-  IMAGE_REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
+  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}/${{ secrets.IMAGE_REGISTRY_USER }}
+  IMAGE_REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
+  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
 
   # 🖊️ EDIT to specify custom tags for the container image, or default tags will be generated below.
   IMAGE_TAGS: ""
@@ -85,142 +85,118 @@ jobs:
       SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
 
     steps:
-      - name: Check for required secrets
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const secrets = {
-              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
-              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
-            };
-            
-            const GHCR = "ghcr.io";
-            if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
-              core.info(`Image registry is ${GHCR} - no registry password required`);
+    - name: Check for required secrets
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const secrets = {
+            OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
+            OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
+          };
+
+          const GHCR = "ghcr.io";
+          if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
+            core.info(`Image registry is ${GHCR} - no registry password required`);
+          }
+          else {
+            core.info("A registry password is required");
+            secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;
+          }
+
+          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
+            if (value.length === 0) {
+              core.error(`Secret "${name}" is not set`);
+              return true;
             }
-            else {
-              core.info("A registry password is required");
-              secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;
-            }
-            
-            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
-              if (value.length === 0) {
-                core.error(`Secret "${name}" is not set`);
-                return true;
-              }
-              core.info(`✔️ Secret "${name}" is set`);
-              return false;
-            });
-            
-            if (missingSecrets.length > 0) {
-              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
-                "You can add it using:\n" +
-                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
-                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
-                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
-            }
-            else {
-              core.info(`✅ All the required secrets are set`);
-            }
+            core.info(`✔️ Secret "${name}" is set`);
+            return false;
+          });
 
-      - name: Check out repository
-        uses: actions/checkout@v4
+          if (missingSecrets.length > 0) {
+            core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
+              "You can add it using:\n" +
+              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
+              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
+              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
+          }
+          else {
+            core.info(`✅ All the required secrets are set`);
+          }
 
-      - name: Determine app name
-        if: env.APP_NAME == ''
-        run: |
-          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
+    - name: Check out repository
+      uses: actions/checkout@v4
 
-      - name: Determine image tags
-        if: env.IMAGE_TAGS == ''
-        run: |
-          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
+    - name: Determine app name
+      if: env.APP_NAME == ''
+      run: |
+        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
 
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: 'zulu'
+    - name: Determine image tags
+      if: env.IMAGE_TAGS == ''
+      run: |
+        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
 
-      - name: Build with Maven
-        run: mvn package -Dquarkus.package.type=fast-jar
+    # https://github.com/redhat-actions/buildah-build#readme
+    - name: Build from Dockerfile
+      id: build-image
+      uses: redhat-actions/buildah-build@v2
+      with:
+        image: ${{ env.APP_NAME }}
+        tags: ${{ env.IMAGE_TAGS }}
 
-      # https://github.com/redhat-actions/buildah-build#readme
-      - name: Build from Dockerfile
-        id: build-image
-        uses: redhat-actions/buildah-build@v2
-        with:
-          image: ${{ env.APP_NAME }}
-          tags: ${{ env.IMAGE_TAGS }}
+        # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
+        # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
+        # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
+        dockerfiles: |
+          ./Dockerfile
 
-          # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
-          # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
-          # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
-          dockerfiles: |
-            ./src/main/docker/Dockerfile.jvm
+    # https://github.com/redhat-actions/push-to-registry#readme
+    - name: Push to registry
+      id: push-image
+      uses: redhat-actions/push-to-registry@v2
+      with:
+        image: ${{ steps.build-image.outputs.image }}
+        tags: ${{ steps.build-image.outputs.tags }}
+        registry: ${{ env.IMAGE_REGISTRY }}
+        username: ${{ env.IMAGE_REGISTRY_USER }}
+        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
 
-      - name: Log variables in console
-        id: log-variables
-        run: |
-          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY}"
-          echo "IMAGE_REGISTRY_USER=${IMAGE_REGISTRY_USER}"
-          echo "IMAGE_REGISTRY_PASSWORD=${IMAGE_REGISTRY_PASSWORD}"
-          echo "OPENSHIFT_SERVER=${OPENSHIFT_SERVER}"
-          echo "OPENSHIFT_TOKEN=${OPENSHIFT_TOKEN}"
-          echo "OPENSHIFT_NAMESPACE=${OPENSHIFT_NAMESPACE}"
-          echo "APP_NAME=${APP_NAME}"
-          echo "APP_PORT=${APP_PORT}"
-          echo "IMAGE_TAGS=${IMAGE_TAGS}"
-          echo "ROUTE=${ROUTE}"
-          echo "SELECTOR=${SELECTOR}"
+    # The path the image was pushed to is now stored in ${{ steps.push-image.outputs.registry-path }}
 
-      # https://github.com/redhat-actions/push-to-registry#readme
-      - name: Push to registry
-        id: push-image
-        uses: redhat-actions/push-to-registry@v2
-        with:
-          image: ${{ steps.build-image.outputs.image }}
-          tags: ${{ steps.build-image.outputs.tags }}
-          registry: ${{ env.IMAGE_REGISTRY }}
-          username: ${{ env.IMAGE_REGISTRY_USER }}
-          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
+    - name: Install oc
+      uses: redhat-actions/openshift-tools-installer@v1
+      with:
+        oc: 4
 
-      # The path the image was pushed to is now stored in ${{ steps.push-image.outputs.registry-path }}
+    # https://github.com/redhat-actions/oc-login#readme
+    - name: Log in to OpenShift
+      uses: redhat-actions/oc-login@v1
+      with:
+        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+        insecure_skip_tls_verify: true
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-      - name: Install oc
-        uses: redhat-actions/openshift-tools-installer@v1
-        with:
-          oc: 4
+    # This step should create a deployment, service, and route to run your app and expose it to the internet.
+    # https://github.com/redhat-actions/oc-new-app#readme
+    - name: Create and expose app
+      id: deploy-and-expose
+      uses: redhat-actions/oc-new-app@v1
+      with:
+        app_name: ${{ env.APP_NAME }}
+        image: ${{ steps.push-image.outputs.registry-path }}
+        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+        port: ${{ env.APP_PORT }}
 
-      # https://github.com/redhat-actions/oc-login#readme
-      - name: Log in to OpenShift
-        uses: redhat-actions/oc-login@v1
-        with:
-          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-          insecure_skip_tls_verify: true
-          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-
-      # This step should create a deployment, service, and route to run your app and expose it to the internet.
-      # https://github.com/redhat-actions/oc-new-app#readme
-      - name: Create and expose app
-        id: deploy-and-expose
-        uses: redhat-actions/oc-new-app@v1
-        with:
-          app_name: ${{ env.APP_NAME }}
-          image: ${{ steps.push-image.outputs.registry-path }}
-          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-          port: ${{ env.APP_PORT }}
-
-      - name: Print application URL
-        env:
-          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-        run: |
-          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-          echo
-          echo "======================== Your application is available at: ========================"
-          echo ${{ env.ROUTE }}
-          echo "==================================================================================="
-          echo
-          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
+        echo
+        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
