chore: debug pipeline

diff --git a/.github/workflows/ci-cd-release.yml b/.github/workflows/ci-cd-release.yml
--- a/.github/workflows/ci-cd-release.yml
+++ b/.github/workflows/ci-cd-release.yml
@@ -21,81 +21,6 @@ on:
 
 jobs:
 
-  build:
-    name: Build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: 'zulu'
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Build
-        run: mvn clean install
-  
-  unit-tests-sonar:
-    name: Unit tests & Sonar
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: 'zulu'
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Run tests
-        run: mvn clean test -Pcoverage
-      - name: Cache SonarQube packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: SonarCloud Build and analyze
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Salle-models-de-desenvolupament_mdas-ci-cd-hello-world -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
-  
-  integration-tests:
-    name: Integration tests
-    runs-on: ubuntu-latest
-    needs: unit-tests-sonar
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: 21
-          distribution: 'zulu'
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Run tests
-        run: mvn clean verify
-  
   versioning:
     name: Semantic Release versioning
     permissions:
@@ -132,9 +57,90 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          VERSION=$(npx semantic-release --dry-run | grep "next release" | awk '{print $4}')
-          echo "IMAGE_TAGS=$VERSION-${GITHUB_SHA::12} latest" | tee -a $GITHUB_ENV
-          echo "BUILD_IMAGE_TAG=$VERSION-${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
+          VERSION=$(npx semantic-release --dry-run | grep "next release version" | awk '{print $4}')
+          if [ -z "$VERSION" ]; then
+            echo "Error: No se pudo obtener la versión." >&2
+            exit 1
+          fi
+          echo "IMAGE_TAGS=$VERSION-${GITHUB_SHA::12} latest" >> $GITHUB_ENV
+          echo "BUILD_IMAGE_TAG=$VERSION-${GITHUB_SHA::12}" >> $GITHUB_ENV
+
+  # build:
+  #   name: Build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Set up JDK 21
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: 21
+  #         distribution: 'zulu'
+  #     - name: Cache Maven packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.m2
+  #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+  #         restore-keys: ${{ runner.os }}-m2
+  #     - name: Build
+  #       run: mvn clean install
+  
+  # unit-tests-sonar:
+  #   name: Unit tests & Sonar
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Set up JDK 21
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: 21
+  #         distribution: 'zulu'
+  #     - name: Cache Maven packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.m2
+  #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+  #         restore-keys: ${{ runner.os }}-m2
+  #     - name: Run tests
+  #       run: mvn clean test -Pcoverage
+  #     - name: Cache SonarQube packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.sonar/cache
+  #         key: ${{ runner.os }}-sonar
+  #         restore-keys: ${{ runner.os }}-sonar
+  #     - name: SonarCloud Build and analyze
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Salle-models-de-desenvolupament_mdas-ci-cd-hello-world -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
+  
+  # integration-tests:
+    # name: Integration tests
+    # runs-on: ubuntu-latest
+    # needs: unit-tests-sonar
+    # steps:
+    #   - uses: actions/checkout@v4
+    #     with:
+    #       fetch-depth: 0
+    #   - name: Set up JDK 21
+    #     uses: actions/setup-java@v4
+    #     with:
+    #       java-version: 21
+    #       distribution: 'zulu'
+    #   - name: Cache Maven packages
+    #     uses: actions/cache@v4
+    #     with:
+    #       path: ~/.m2
+    #       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+    #       restore-keys: ${{ runner.os }}-m2
+    #   - name: Run tests
+    #     run: mvn clean verify
+  
+  # VERSIONING GOES HERE
   
   artifact:
     name: Artifact
