fix(ci): reference version env

diff --git a/.github/workflows/ci-cd-release.yml b/.github/workflows/ci-cd-release.yml
--- a/.github/workflows/ci-cd-release.yml
+++ b/.github/workflows/ci-cd-release.yml
@@ -55,11 +55,16 @@ jobs:
         run: |
           export VERSION=$(npx semantic-release --dry-run | grep "next release version is" | awk '{print $5}')
           if [ -z "$VERSION" ]; then
-            echo "Error: No se pudo obtener la versión." >&2
+            echo "Failed to determine version" >&2
             exit 1
           fi
           echo "IMAGE_TAGS=$VERSION-${GITHUB_SHA::12} latest" >> $GITHUB_ENV
           echo "BUILD_IMAGE_TAG=$VERSION-${GITHUB_SHA::12}" >> $GITHUB_ENV
+      - name: Perform release
+        id: perform_release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npx semantic-release
 
   # TODO: build:
   #   name: Build
@@ -144,8 +149,6 @@ jobs:
     needs: versioning # TODO: [integration-tests, versioning]
     outputs:
       version: ${{ needs.versioning.outputs.version }}
-    env:
-      VERSION: ${{ needs.versioning.outputs.version }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -184,8 +187,6 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     needs: [artifact]
-    env:
-      VERSION: ${{ needs.artifact.outputs.version }}
 
     outputs:
       ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
